apiVersion: networking.k8s.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging-account-private-key
    solvers:
      - http01:
          ingress:
            class: nginx
